/*
 * data.js — Word packs for The Imposter.
 *
 * Each category has:
 *   - id:    stable identifier (used in settings persistence)
 *   - name:  display label
 *   - icon:  emoji shown on the chip
 *   - words: array of secret words. Each word may carry an optional hint that is
 *            shown to the imposter when "Hint mode" is enabled. Hints are written
 *            to be suggestive but never a giveaway.
 *
 * Words are intentionally concrete and guessable so that one-word clues are fun.
 */

const GAME_DATA = {
  categories: [
    {
      id: "food",
      name: "Food & Drink",
      icon: "🍔",
      words: [
        { word: "Pizza", hint: "Italian" },
        { word: "Sushi", hint: "Japanese" },
        { word: "Hamburger", hint: "Fast food" },
        { word: "Tacos", hint: "Mexican" },
        { word: "Pancakes", hint: "Breakfast" },
        { word: "Spaghetti", hint: "Pasta" },
        { word: "Ice Cream", hint: "Dessert" },
        { word: "Popcorn", hint: "Cinema snack" },
        { word: "Coffee", hint: "Morning drink" },
        { word: "Chocolate", hint: "Sweet" },
        { word: "Watermelon", hint: "Summer fruit" },
        { word: "Pickle", hint: "Sour" },
        { word: "Bacon", hint: "Breakfast meat" },
        { word: "Ramen", hint: "Noodle soup" },
        { word: "Doughnut", hint: "Has a hole" },
        { word: "Avocado", hint: "Green, trendy" },
        { word: "Burrito", hint: "Wrapped" },
        { word: "Cheese", hint: "Dairy" },
        { word: "Lemonade", hint: "Cold drink" },
        { word: "Cereal", hint: "With milk" },
      ],
    },
    {
      id: "animals",
      name: "Animals",
      icon: "🦁",
      words: [
        { word: "Elephant", hint: "Very big" },
        { word: "Penguin", hint: "Cold places" },
        { word: "Kangaroo", hint: "Australia" },
        { word: "Octopus", hint: "Many arms" },
        { word: "Giraffe", hint: "Tall" },
        { word: "Dolphin", hint: "Ocean" },
        { word: "Cheetah", hint: "Very fast" },
        { word: "Owl", hint: "Nocturnal" },
        { word: "Sloth", hint: "Slow" },
        { word: "Shark", hint: "Predator" },
        { word: "Hedgehog", hint: "Spiky" },
        { word: "Flamingo", hint: "Pink" },
        { word: "Chameleon", hint: "Color change" },
        { word: "Panda", hint: "Bamboo" },
        { word: "Crocodile", hint: "Reptile" },
        { word: "Bumblebee", hint: "Buzzes" },
        { word: "Wolf", hint: "Pack animal" },
        { word: "Jellyfish", hint: "Stings" },
        { word: "Hamster", hint: "Pet, small" },
        { word: "Eagle", hint: "Bird of prey" },
      ],
    },
    {
      id: "places",
      name: "Places",
      icon: "🗺️",
      words: [
        { word: "Beach", hint: "Sandy" },
        { word: "Hospital", hint: "Health" },
        { word: "Library", hint: "Quiet" },
        { word: "Airport", hint: "Travel" },
        { word: "Museum", hint: "Exhibits" },
        { word: "Casino", hint: "Gambling" },
        { word: "Gym", hint: "Fitness" },
        { word: "Cinema", hint: "Movies" },
        { word: "Zoo", hint: "Animals" },
        { word: "Bakery", hint: "Bread" },
        { word: "Volcano", hint: "Eruption" },
        { word: "Desert", hint: "Dry" },
        { word: "Castle", hint: "Medieval" },
        { word: "Submarine", hint: "Underwater" },
        { word: "Stadium", hint: "Sports" },
        { word: "Lighthouse", hint: "Coastal" },
        { word: "Pharmacy", hint: "Medicine" },
        { word: "Aquarium", hint: "Fish tanks" },
        { word: "Subway", hint: "Underground" },
        { word: "Rooftop", hint: "Up high" },
      ],
    },
    {
      id: "movies",
      name: "Movies & TV",
      icon: "🎬",
      words: [
        { word: "Titanic", hint: "Ship" },
        { word: "Jurassic Park", hint: "Dinosaurs" },
        { word: "The Lion King", hint: "Animated" },
        { word: "Star Wars", hint: "Space" },
        { word: "Frozen", hint: "Snow" },
        { word: "Harry Potter", hint: "Magic" },
        { word: "Avatar", hint: "Blue aliens" },
        { word: "The Matrix", hint: "Simulation" },
        { word: "Breaking Bad", hint: "TV drama" },
        { word: "Friends", hint: "Sitcom" },
        { word: "Stranger Things", hint: "80s, eerie" },
        { word: "Game of Thrones", hint: "Dragons" },
        { word: "Spider-Man", hint: "Superhero" },
        { word: "Toy Story", hint: "Toys" },
        { word: "The Office", hint: "Workplace" },
        { word: "Pirates of the Caribbean", hint: "Pirates" },
        { word: "Shrek", hint: "Ogre" },
        { word: "Inception", hint: "Dreams" },
        { word: "Squid Game", hint: "Survival" },
        { word: "Finding Nemo", hint: "Fish" },
      ],
    },
    {
      id: "sports",
      name: "Sports",
      icon: "⚽",
      words: [
        { word: "Soccer", hint: "Ball, feet" },
        { word: "Basketball", hint: "Hoop" },
        { word: "Tennis", hint: "Racket" },
        { word: "Boxing", hint: "Gloves" },
        { word: "Golf", hint: "Clubs" },
        { word: "Swimming", hint: "Pool" },
        { word: "Surfing", hint: "Waves" },
        { word: "Skiing", hint: "Snow" },
        { word: "Bowling", hint: "Pins" },
        { word: "Archery", hint: "Bow" },
        { word: "Cycling", hint: "Bike" },
        { word: "Gymnastics", hint: "Flips" },
        { word: "Hockey", hint: "Puck" },
        { word: "Cricket", hint: "Bat, wicket" },
        { word: "Climbing", hint: "Rocks" },
        { word: "Skateboarding", hint: "Board" },
        { word: "Volleyball", hint: "Net" },
        { word: "Fencing", hint: "Sword" },
        { word: "Marathon", hint: "Long run" },
        { word: "Darts", hint: "Throwing" },
      ],
    },
    {
      id: "objects",
      name: "Everyday Objects",
      icon: "🧦",
      words: [
        { word: "Umbrella", hint: "Rain" },
        { word: "Toothbrush", hint: "Hygiene" },
        { word: "Candle", hint: "Light" },
        { word: "Mirror", hint: "Reflection" },
        { word: "Scissors", hint: "Cutting" },
        { word: "Pillow", hint: "Sleep" },
        { word: "Backpack", hint: "Carry" },
        { word: "Stapler", hint: "Office" },
        { word: "Headphones", hint: "Audio" },
        { word: "Wallet", hint: "Money" },
        { word: "Ladder", hint: "Climb" },
        { word: "Compass", hint: "Direction" },
        { word: "Battery", hint: "Power" },
        { word: "Telescope", hint: "Stars" },
        { word: "Vacuum", hint: "Cleaning" },
        { word: "Hammer", hint: "Tool" },
        { word: "Sunglasses", hint: "Eyes" },
        { word: "Keyboard", hint: "Typing" },
        { word: "Thermometer", hint: "Temperature" },
        { word: "Suitcase", hint: "Packing" },
      ],
    },
    {
      id: "jobs",
      name: "Jobs",
      icon: "🧑‍🚀",
      words: [
        { word: "Astronaut", hint: "Space" },
        { word: "Firefighter", hint: "Emergencies" },
        { word: "Chef", hint: "Kitchen" },
        { word: "Pilot", hint: "Aircraft" },
        { word: "Surgeon", hint: "Operations" },
        { word: "Teacher", hint: "School" },
        { word: "Detective", hint: "Mysteries" },
        { word: "Plumber", hint: "Pipes" },
        { word: "Magician", hint: "Tricks" },
        { word: "Lawyer", hint: "Court" },
        { word: "Barber", hint: "Hair" },
        { word: "Farmer", hint: "Crops" },
        { word: "Journalist", hint: "News" },
        { word: "Architect", hint: "Buildings" },
        { word: "Dentist", hint: "Teeth" },
        { word: "Lifeguard", hint: "Water safety" },
        { word: "Electrician", hint: "Wiring" },
        { word: "Photographer", hint: "Camera" },
        { word: "Veterinarian", hint: "Animals" },
        { word: "Carpenter", hint: "Wood" },
      ],
    },
    {
      id: "tech",
      name: "Technology",
      icon: "💻",
      words: [
        { word: "Smartphone", hint: "Pocket device" },
        { word: "Wi-Fi", hint: "Wireless" },
        { word: "Robot", hint: "Automation" },
        { word: "Drone", hint: "Flying" },
        { word: "Bluetooth", hint: "Pairing" },
        { word: "Password", hint: "Security" },
        { word: "Emoji", hint: "Messaging" },
        { word: "Podcast", hint: "Audio show" },
        { word: "Hashtag", hint: "Social media" },
        { word: "Selfie", hint: "Photo" },
        { word: "Algorithm", hint: "Steps" },
        { word: "Firewall", hint: "Protection" },
        { word: "Cloud", hint: "Storage" },
        { word: "Joystick", hint: "Gaming" },
        { word: "Touchscreen", hint: "Tap" },
        { word: "Webcam", hint: "Video" },
        { word: "Server", hint: "Hosting" },
        { word: "Charger", hint: "Power up" },
        { word: "Spreadsheet", hint: "Rows, columns" },
        { word: "Printer", hint: "Paper" },
      ],
    },
    {
      id: "nature",
      name: "Nature",
      icon: "🌿",
      words: [
        { word: "Rainbow", hint: "Colors" },
        { word: "Waterfall", hint: "Falling water" },
        { word: "Cactus", hint: "Prickly" },
        { word: "Glacier", hint: "Ice" },
        { word: "Tornado", hint: "Spinning" },
        { word: "Coral Reef", hint: "Underwater" },
        { word: "Mushroom", hint: "Fungus" },
        { word: "Lightning", hint: "Storm" },
        { word: "Canyon", hint: "Deep gorge" },
        { word: "Sunflower", hint: "Tall flower" },
        { word: "Iceberg", hint: "Floating ice" },
        { word: "Meteor", hint: "Falling rock" },
        { word: "Quicksand", hint: "Sinking" },
        { word: "Geyser", hint: "Hot spring" },
        { word: "Snowflake", hint: "Unique" },
        { word: "Jungle", hint: "Dense forest" },
        { word: "Aurora", hint: "Northern lights" },
        { word: "Swamp", hint: "Wetland" },
        { word: "Volcano", hint: "Lava" },
        { word: "Tide", hint: "Ocean rise" },
      ],
    },
    {
      id: "spooky",
      name: "Spooky",
      icon: "👻",
      words: [
        { word: "Vampire", hint: "Fangs" },
        { word: "Zombie", hint: "Undead" },
        { word: "Werewolf", hint: "Full moon" },
        { word: "Ghost", hint: "Haunting" },
        { word: "Witch", hint: "Spells" },
        { word: "Mummy", hint: "Wrapped" },
        { word: "Skeleton", hint: "Bones" },
        { word: "Haunted House", hint: "Scary place" },
        { word: "Pumpkin", hint: "Carved" },
        { word: "Spider", hint: "Web" },
        { word: "Frankenstein", hint: "Stitched" },
        { word: "Graveyard", hint: "Tombstones" },
        { word: "Cauldron", hint: "Brewing" },
        { word: "Black Cat", hint: "Bad luck" },
        { word: "Bat", hint: "Flies at night" },
        { word: "Cobweb", hint: "Dusty" },
        { word: "Potion", hint: "Bubbling" },
        { word: "Scarecrow", hint: "Field" },
        { word: "Goblin", hint: "Mischief" },
        { word: "Crypt", hint: "Tomb" },
      ],
    },
  ],
};

// Expose to the global scope for the non-module script setup.
window.GAME_DATA = GAME_DATA;
